### ISSUE TITLE
Broken pip install

### ISSUE THREAD

**Issue by SamusRam** [facebookresearch/esm#17]
Hello,

thank you for the amazing work!

I just would like to let you know, that the latest modification of README has broken pip install, as there is a README.**rst** among data_files in the setup.py, but now the repo has README.**md** instead.

Best regards,
Raman

**Comment by tomsercu** [comment]
Thanks a ton for flagging! Should be fixed now :)

**Comment by SamusRam** [comment]
Wow, that was quick :) The install works like a charm, thanks!

P.S. Just so you know, I wasn't able to pip install your awesome library in a Kaggle notebook due to an issue with the latest version of typing library. On my local machine pip install worked without any problem, I have typing==3.7.4.2. Kaggle currently has typing==3.7.4.3.

In the Kaggle notebook I had to 
```
!pip uninstall -y typing
!pip install git+https://github.com/facebookresearch/esm.git
```

Just so you know, I was not able to 
`!pip install typing==3.7.2
`
as this version seems to be removed from pypi. I tried a couple of older versions of the typing library, but I faced the same issue with the esm install.

Not having the typing-lib available is the least possible price for playing with your fantastic results, just a heads-up :)

**Comment by tomsercu** [comment]
I'm not too familiar with kaggle notebooks, checking it out now, and getting an error as well;
`ERROR: Command errored out with exit status 128: git clone -q https://github.com/facebookresearch/esm.git /tmp/pip-req-build-2n1gcvxy Check the logs for full command output.`
 Can you point me to the logs / how you diagnosed this is due to `typing`? I'm confused what typing got to do with this - we're not requiring any specific version of typing and not using any fancy features..

**Comment by SamusRam** [comment]
Sorry for the late reply due to the night in Europe.
I believe more projects are facing the same issues, moreover I managed to replicate the issue locally after upgrading `typing`. Could you please let me know here, in case `black` turn out to be the root cause? Thank you and good luck with the bug hunt!

**Comment by tomsercu** [comment]
I looked into it only a little bit, but since black comes pre-installed and I can run it without issue that seems unrelated.
Ok and poking a bit further it seems like there are just 2 conflicting packages `typing` pre-installed in their conda env, which of course gives trouble.. I'd just assume kaggle will figure it out and will update their docker image.
![image](https://user-images.githubusercontent.com/4034984/102436676-19eeae80-3fe7-11eb-9a7f-fe11fa5992bd.png)

**Comment by SamusRam** [comment]
Hi Tom,

thank you for the time you invested in looking into the issue! It's very much appreciated! I've shared all the insights with kaggle support.

But mainly, again, thank you so much for your awesome work! The result amazed me so much that I felt an urge to play with it myself and to check what the self-learned embeddings are capable of (that was the reason why I wanted to install the package into kaggle kernel) I was playing with your model on top of a tiny dataset of approx. 70 proteins there. And in the end, your work amazed me first hand :) 

Just in case you might be curious about the kind of fun people are having with your model in their leisure time, here's a link to my brief experiments: https://www.kaggle.com/samusram/fair-transformer-understands-proteins-let-s-check?scriptVersionId=49615485

Best regards,
Raman

**Comment by joshim5** [comment]
@SamusRam, this is very cool work! Thanks for sharing it with us. Feel free to try our newest model ESM-1b (`esm1b_t33_650M_UR50S`) which should give you even stronger results. Excited to see what you build with this next!

**Comment by SamusRam** [comment]
@joshim5, thank you for the kind words, you made my day! And thanks for the awesome work you're doing, I'm really looking forward to more of your papers!

p.s. I've briefly experimented with ESM-1b, thank you for the suggestion! The final prediction results are similar, but it might be due to the tiny dataset limitations. I still find the results enabled by your embeddings astonishing!
