### ISSUE TITLE
download the model weights to local

### ISSUE THREAD

**Issue by lzhangUT** [facebookresearch/esm#174]
Hi, @rmrao, 
I am interested in using the esm-iv models (1-5), it takes a long time to download the model/model weights every time when I run one sequence. I wonder if I can download the model weights (or model) into my local workspace, as in Azure Databricks? so It would read the model very quickly when I need to run a lot of sequences. if so, what would be the code to do that?
THank you.

**Comment by lzhangUT** [comment]
Hi Roshan,
Thanks for th suggestion, I changed the cache directory before downloading,
it seems like it is  a little bit quicker.
when loading the model, I always get this warning:
/databricks/python/lib/python3.8/site-packages/esm/pretrained.py:134:
UserWarning: Regression weights not found, predicting contacts will not
produce correct results.
warnings.warn("Regression weights not found, predicting contacts will not
produce correct results.")

Should I be concerned about this warning?
Thanks.

**Comment by rmrao** [comment]
You can ignore the warning. (No regression weights are provided for ESM-1v because its not designed for contact prediction. We should probably just throw an error if you try to do contact prediction with ESM-1v models.)

As for the speed - after the first time it downloads the model, it should never download it again. If you're still seeing slowdowns you could change the loading code to the local loading version (`esm.pretrained.load_model_and_alphabet_local(<path/to/file>)`) to ensure that it's not downloading anything.

It's possible when using a cloud setup that the transfer of the model weights from storage actually takes quite a while (the weights for each individual model are ~10GB). I'm not familiar enough with Azure to suggest solutions if this is the issue.

**Comment by lzhangUT** [comment]
Thank you, @rmrao 
everything works now.
I do have another question: 
when I use the esm-iv models (1-5) predictions for validation/test, in the paper, it was mentioned that the average value of the five model predictions or/and the ensemble of the five model was compared with the experimental data. It is easy to think about the average of the five models, what is the ensemble value? Is there another model to count for the ensemble or different calculation from the five models to count for?
Thanks

**Comment by rmrao** [comment]
As far as I'm aware the ensemble prediction is the average of the five models. If there's a part of the paper that implies something different, let me know and I can take a look.

I actually didn't run the bootstrapping experiment so I'm not sure of the details right now. @robert-verkuil, do you happen to know? If not I'll try to figure it out but it may take a week or so.

**Comment by tomsercu** [comment]
Hi @lzhangUT , thanks for your interest in our models!
The follow-up questions would better belong int he discussion forums, but let me quickly answer:
* Average of models: first compute rhos, then average. Vs ensemble: average predictions, ie different ranking before computing the spearman rho.
* Bootstrap: for a given protein, the DMS size is N (typically order of thousands of mutations). The bootstrap sample size is N, sampled with replacement.  "mean ± std of 20 bootstrapped samples" means we repeat this bootstrap sample 20 times, then compute rho for each of the 20 bootstrap samples, compute mean and std.

Hope that helps - If anything is unclear you can open a gh discussion and we can follow up there!
