### ISSUE TITLE
Odd Prec?

### ISSUE THREAD

**Issue by 227BaronChen** [facebookresearch/esm#28]
I have a small problem. In my cognition, the prediction of long-range residue contact is more difficult than the short-range one, but the indicators given in this paper are just the opposite. If anyone can explain it, I would be very grateful.

**Comment by nasserhashemi** [comment]
I have checked the contact map over 25000 target based on single sequence; and the mean precision of long-range was lower than short-range as expected;

**Comment by 227BaronChen** [comment]
Okay, but why Table 1 and Table 2 in the paper are different? Did I make a mistake?

**Comment by nasserhashemi** [comment]
I think, the termination of short-range has some kind of inconsistency; I think when people talked about short-range they consider any i and j which |i - j| > 5; however; in the paper they consider 5<|i-j|<12; I think it is the reason;

**Comment by rmrao** [comment]
Yes - in the paper we specifically consider short range contacts to be those in the range 5 < |i - j| < 12, rather than |i - j| > 5. Note this is consistent with CASP/etc. which refer to |i - j| > 5 as SR + MR + LR contacts, rather than specifically short-range contacts. This value can be quite low because there are often fewer than L short or medium range contacts, so it may be impossible to reach a precision of 1.

**Comment by nasserhashemi** [comment]
yes, you are right, so the paper I mentioned was inconsistent:)

**Comment by tomsercu** [comment]
seems like this is resolved - but feel free to open a discussion [here](https://github.com/facebookresearch/esm/discussions)!
